# Global build settings

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]

  # SPA - serve all URLs with index file and give HTTP 200
  from = "/*"
  to = "/index.html"
  status = 200